import { StyleSheet } from 'react-native'
import { colors, radii } from './theme'

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
    padding: 20,
  },
  containerCentered: {
    flex: 1,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },

  title: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 8,
    color: colors.textPrimary,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 15,
    marginBottom: 24,
    color: colors.textSecondary,
    lineHeight: 21,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 10,
    color: colors.textSecondary,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },

  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    padding: 16,
    marginBottom: 16,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.surface,
  },
  inputCentered: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    padding: 16,
    marginBottom: 16,
    fontSize: 16,
    textAlign: 'center',
    color: colors.textPrimary,
    backgroundColor: colors.surface,
  },

  inlineButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 24,
    gap: 8,
  },
  inlineButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.full,
    backgroundColor: colors.surface,
    alignItems: 'center',
  },
  inlineButtonSelected: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  inlineButtonText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '500',
  },
  inlineButtonTextSelected: {
    color: colors.bg,
    fontSize: 14,
    fontWeight: '600',
  },

  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 12,
  },
  stepperLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textSecondary,
    width: 30,
  },
  stepperButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.elevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {
    fontSize: 20,
    color: colors.textPrimary,
    lineHeight: 24,
  },
  stepperValue: {
    width: 44,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  sliderLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 16,
  },

  tagInputContainer: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 100,
  },
  tagInput: {
    color: colors.textPrimary,
    fontSize: 16,
    padding: 6,
  },
  tag: {
    backgroundColor: colors.elevated,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: radii.full,
    margin: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tagText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  tagRemove: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '400',
  },

  profileHeader: {
    alignItems: 'center',
    paddingTop: 24,
    marginBottom: 24,
  },
  profileImageContainer: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: colors.border,
  },
  profileImage: {
    width: 64,
    height: 64,
  },
  profileName: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  sectionBox: {
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 12,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  profileFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  profileFieldRowLast: {
    borderBottomWidth: 0,
  },
  profileFieldIcon: {
    width: 24,
    marginRight: 12,
  },
  profileFieldContent: {
    flex: 1,
  },
  profileFieldLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
    marginBottom: 2,
  },
  profileFieldValue: {
    fontSize: 15,
    color: colors.textPrimary,
  },
  profileFieldValueEmpty: {
    fontSize: 15,
    color: colors.textTertiary,
    fontStyle: 'italic',
  },
  appConnectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  appConnectionRowLast: {
    borderBottomWidth: 0,
  },
  appConnectionInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  appConnectionName: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.textPrimary,
    marginLeft: 12,
  },
  appConnectionStatus: {
    fontSize: 13,
    color: colors.textSecondary,
    marginLeft: 12,
  },
  settingsButton: {
    padding: 8,
  },

  runnerCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  runnerCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  runnerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.elevated,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  runnerHeaderText: {
    flex: 1,
  },
  runnerName: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  runnerNeighborhood: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2,
  },
  runnerMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 4,
    gap: 6,
  },
  runnerChip: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radii.full,
    backgroundColor: colors.elevated,
  },
  runnerChipText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  runnerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: radii.full,
    backgroundColor: colors.elevated,
    gap: 4,
  },
  runnerPillLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  runnerPillValue: {
    fontSize: 12,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  runnerGoalsRow: {
    marginTop: 10,
  },
  runnerGoalsLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  runnerGoalsText: {
    fontSize: 14,
    color: colors.textPrimary,
  },
})
